/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.hrdb.*;

/**
 * Service object for domain model class EVdetails.
 * @see com.hrdb.EVdetails
 */

public interface EVdetailsService {

	/**
	 * Finds all evdetailss.
	 * 
	 * @return A list of evdetailss.
	 */
	public Page<EVdetails> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<EVdetails> findAll(Pageable pageable);
	
	/**
	 * Finds evdetails by id.
	 * 
	 * @param id
	 *            The id of the wanted evdetails.
	 * @return The found evdetails. If no evdetails is found, this method returns
	 *         null.
	 */
	public EVdetails findById(EVdetailsId id) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the evdetailss in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the evdetails.
	 */

	public long countAll();


    public Page<EVdetails> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

